task_manager/labels/urls.py
from django.urls import path

from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='list'),
    path('create/', views.CreateLabelView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateLabelView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteLabelView.as_view(), name='delete'),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='list'),
    path('<int:pk>/', views.TaskView.as_view(), name='preview'),
    path('create/', views.CreateTaskView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateTaskView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteTaskView.as_view(), name='delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from task_manager import views

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
]

task_manager/users/urls.py
from django.urls import path

from task_manager.users import views

app_name = "users"

urlpatterns = [
    path('', views.UserListView.as_view(), name='list'),
    path('create/', views.RegistrationView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateUserView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteUserView.as_view(), name='delete'),
]

task_manager/labels/models.py
"""Labels models."""

from django.db import models
from django.utils import timezone


class Label(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(unique=True, max_length=100)
    date_created = models.DateTimeField(default=timezone.now)

task_manager/models.py
"""Task Manager models."""

task_manager/statuses/models.py
"""Statuses models."""

from django.db import models
from django.utils import timezone


class Status(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(unique=True, max_length=100)
    date_created = models.DateTimeField(default=timezone.now)

task_manager/tasks/models.py
"""Tasks models."""

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from task_manager.statuses.models import Status
from task_manager.labels.models import Label


class Task(models.Model):
    name = models.CharField(unique=True, max_length=100)
    description = models.TextField(max_length=1000)
    author = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='created_tasks_set',
    )
    implementer = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='assigned_tasks_set',
    )
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    labels = models.ManyToManyField(Label, through='TaskAndLabel')
    date_created = models.DateTimeField(default=timezone.now)


class TaskAndLabel(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    label = models.ForeignKey(Label, on_delete=models.PROTECT)

task_manager/users/models.py
from django.db import models

task_manager/labels/forms.py
"""Labels forms."""
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from task_manager.labels.models import Label


class LabelForm(ModelForm):
    class Meta:
        model = Label
        fields = ('name',)
        localized_fields = ('name',)
        labels = {"name": _("Name")}

task_manager/statuses/forms.py
"""Statuses forms."""
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from task_manager.statuses.models import Status


class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ('name',)
        localized_fields = ('name',)
        labels = {"name": _("Name")}

task_manager/tasks/forms.py
"""Tasks forms."""
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from task_manager.tasks.models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        exclude = [
            'author',
            'date_created',
        ]
        localized_fields = (
            'name',
            'implementer',
            'description',
            'status',
            'labels',
            )
        labels = {
            'name': _('Name'),
            'implementer': _('Implementer'),
            'description': _('Description'),
            'status': _('Status'),
            'labels': _('Labels'),
            }

task_manager/users/forms.py
"""Task Manager models."""
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
        )

task_manager/labels/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from task_manager.labels.forms import LabelForm
from task_manager.labels.models import Label


class LabelListView(ListView):
    queryset = Label.objects.all()
    template_name = 'labels/list.html'


class CreateLabelView(SuccessMessageMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/create.html'
    success_url = reverse_lazy('labels:list')
    success_message = _('The label is successfully created')


class UpdateLabelView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/update.html'
    success_url = reverse_lazy('labels:list')
    success_message = _('The label is successfully changed')
    permission_denied_message = _(
        'You are not authorized! Please complete the entrance.',
    )


class DeleteLabelView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Label
    template_name = 'labels/delete.html'
    success_url = reverse_lazy('labels:list')
    success_message = _('The label is successfully deleted')
    permission_denied_message = _(
        'You are not authorized! Please complete the entrance.',
    )

task_manager/statuses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from task_manager.statuses.forms import StatusForm
from task_manager.statuses.models import Status


class StatusListView(ListView):
    queryset = Status.objects.all()
    template_name = 'statuses/list.html'


class CreateStatusView(SuccessMessageMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/create.html'
    success_url = reverse_lazy('statuses:list')
    success_message = _('The status is successfully created')


class UpdateStatusView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/update.html'
    success_url = reverse_lazy('statuses:list')
    success_message = _('The status is successfully changed')
    permission_denied_message = _(
        'You are not authorized! Please complete the entrance.',
    )


class DeleteStatusView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Status
    template_name = 'statuses/delete.html'
    success_url = reverse_lazy('statuses:list')
    success_message = _('The status is successfully deleted')
    permission_denied_message = _(
        'You are not authorized! Please complete the entrance.',
    )

task_manager/tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django.views.generic.list import ListView
from django_filters.views import FilterView

from task_manager.tasks.forms import TaskForm
from task_manager.tasks.models import Task
from task_manager.tasks.filters import TaskFilter
from task_manager.users.mixins import AuthorRequiredMixin


class TaskView(DetailView):
    model = Task
    template_name = 'tasks/preview.html'

class TaskListView(FilterView):
    queryset = Task.objects.all()
    template_name = 'tasks/list.html'
    model = Task
    filterset_class = TaskFilter


class CreateTaskView(SuccessMessageMixin, CreateView):
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

    model = Task
    form_class = TaskForm
    template_name = 'tasks/create.html'
    success_url = reverse_lazy('tasks:list')
    success_message = _('The task is successfully created')


class UpdateTaskView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/update.html'
    success_url = reverse_lazy('tasks:list')
    success_message = _('The task is successfully changed')
    permission_denied_message = _(
        'You are not authorized! Please complete the entrance.',
    )


class DeleteTaskView(
    LoginRequiredMixin, AuthorRequiredMixin, SuccessMessageMixin, DeleteView
):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy('tasks:list')
    success_message = _('The task is successfully deleted')
    permission_denied_message = _(
        'You are not authorized! Please complete the entrance.',
    )
    failure_url = reverse_lazy("tasks:list")
    failure_message = _("The task can only be deleted by its author.")

task_manager/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from task_manager.users.forms import UserForm


class UserListView(ListView):
    queryset = User.objects.filter(is_staff=False)
    template_name = 'users/list.html'


class RegistrationView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserForm
    template_name = 'users/create.html'
    success_url = reverse_lazy('login')
    success_message = _('The user is successfully registered')


class UpdateUserView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = UserForm
    template_name = 'users/update.html'
    success_url = reverse_lazy('users:list')
    success_message = _('The user is successfully changed')
    permission_denied_message = _(
        'You are not authorized! Please complete the entrance.',
    )


class DeleteUserView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = User
    template_name = 'users/delete.html'
    success_url = reverse_lazy('users:list')
    success_message = _('The user is successfully deleted')
    permission_denied_message = _(
        'You are not authorized! Please complete the entrance.',
    )

task_manager/views.py
"""Task Manager views."""

from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _


class MessageMixin(object):
    """Add the message to any View descendants."""

    message = ''

    def dispatch(self, request, *args, **kwargs):
        if self.message:
            messages.info(request, self.message)
        return super().dispatch(request, *args, **kwargs)


class UserLoginView(SuccessMessageMixin, LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True
    next_page = 'index'
    success_message = _('You are logged in')


class UserLogoutView(MessageMixin, LogoutView):
    next_page = 'index'
    message = _('You are logged out')

task_manager/templates/tasks/create.html
{% extends 'components/form.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block header %}{% translate 'Create task' %}{% endblock %}
{% block button %}{% translate 'Create' %}{% endblock %}

task_manager/templates/tasks/delete.html
{% extends 'components/delete_form.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block header %}{% translate 'Delete task' %}{% endblock %}
{% block button %}{% translate 'Yes, delete' %}{% endblock %}

{% block confirm_message %}
{% translate 'Are you sure you want to delete' %} "{{ object.name }}"?
{% endblock %}

task_manager/templates/tasks/list.html
{% extends 'components/base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block header %}{% translate "Tasks" %}{% endblock %}

{% block content %}
<a class="nav-link" href="{% url 'tasks:create' %}">{% translate 'Create task' %}</a>
<div class="card mb-3">
  <div class="card-body bg-light">
    <form class="form-inline center" method="get">
      {% bootstrap_field filter.form.status field_class="ml-3 mr-3" %}
      {% bootstrap_field filter.form.implementer field_class="ml-3 mr-3" %}
      {% bootstrap_field filter.form.labels field_class="ml-3 mr-3" %}
      {% bootstrap_field filter.form.my_tasks field_class="mr-3"%}
      {% buttons %}
      <input class="btn btn-primary" type="submit" value="{% translate "Show" %}">
      {% endbuttons %}
    </form>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>{% translate "Name" %}</th>
      <th>{% translate "Status" %}</th>
      <th>{% translate "Author" %}</th>
      <th>{% translate "Implementer" %}</th>
      <th>{% translate "Date of creation" %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for task in filter.qs %}
    <tr>
      <td>{{ task.id }}</td>
      <td><a href="{% url "tasks:preview" task.id %}">{{ task.name }}</a></td>
      <td>{{ task.status }}</td>
      <td>{{ task.author }}</td>
      <td>{{ task.implementer }}</td>
      <td>{{ task.date_created }}</td>
      <td>
        <a href="{% url "tasks:update" task.id %}">{% translate "Change" %}</a>
        <br>
        <a href="{% url "tasks:delete" task.id %}">{% translate "Delete" %}</a>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan=7>{% translate "No tasks yet." %}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

task_manager/templates/tasks/preview.html
{% extends 'components/base.html' %}
{% load i18n %}

{% block header %}{% translate "Tasks preview" %}{% endblock %}

{% block content %}
<div class="card">
  <div class="card-header bg-secondary text-white">
    <h2>{{ object.name }}</h2>
  </div>
  <div class="card-body bg-light">
    <p>{{ object.description }}</p>
    <hr>
    <div class="container">
      <div class="row p-1">
        <div class="col">{% translate "Author" %}</div>
        <div class="col">{{ object.author }}</div>
      </div>
      <div class="row p-1">
        <div class="col">{% translate "Implementer" %}</div>
        <div class="col">{{ object.implementer }}</div>
      </div>
      <div class="row p-1">
        <div class="col">{% translate "Status" %}</div>
        <div class="col">{{ object.status }}</div>
      </div>
      <div class="row p-1">
        <div class="col">{% translate "Date of creation" %}</div>
        <div class="col">{{ object.date_created }}</div>
      </div>
      <div class="row p-1">
        <div class="col">
          {% translate "Labels" %}
          <ul>
          {% for label in object.labels.all %}
            <li>{{ label }}</li>
          {% endfor %}
          </ul>
        </div>
      </div>
      <div class="row p-1">
        <div class="col">
          <a href="{% url "tasks:update" task.id %}">{% translate "Change" %}</a>
          <br>
          <a href="{% url "tasks:delete" task.id %}">{% translate "Delete" %}</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

task_manager/templates/tasks/update.html
{% extends 'components/form.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block header %}{% translate 'Update task' %}{% endblock %}
{% block button %}{% translate 'Update' %}{% endblock %}